// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package catalogdb

import (
	"context"
)

// iteratorForInsertEventSeats implements pgx.CopyFromSource.
type iteratorForInsertEventSeats struct {
	rows                 []InsertEventSeatsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertEventSeats) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertEventSeats) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OrganizerID,
		r.rows[0].EventID,
		r.rows[0].PriceCategoryID,
		r.rows[0].Kind,
		r.rows[0].Section,
		r.rows[0].RowLabel,
		r.rows[0].SeatLabel,
	}, nil
}

func (r iteratorForInsertEventSeats) Err() error {
	return nil
}

func (q *Queries) InsertEventSeats(ctx context.Context, arg []InsertEventSeatsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"event_seats"}, []string{"organizer_id", "event_id", "price_category_id", "kind", "section", "row_label", "seat_label"}, &iteratorForInsertEventSeats{rows: arg})
}
