// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package catalogdb

import (
	"context"
	"time"
)

const createOrganizer = `-- name: CreateOrganizer :one
INSERT INTO organizers (name, slug) VALUES ($1, $2)
RETURNING id, name, slug, created_at
`

type CreateOrganizerParams struct {
	Name string
	Slug string
}

type CreateOrganizerRow struct {
	ID        string
	Name      string
	Slug      string
	CreatedAt time.Time
}

func (q *Queries) CreateOrganizer(ctx context.Context, arg CreateOrganizerParams) (CreateOrganizerRow, error) {
	row := q.db.QueryRow(ctx, createOrganizer, arg.Name, arg.Slug)
	var i CreateOrganizerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const createOwner = `-- name: CreateOwner :one
INSERT INTO organizer_members (organizer_id, email, role) VALUES ($1, $2, 'owner')
RETURNING id
`

type CreateOwnerParams struct {
	OrganizerID string
	Email       string
}

func (q *Queries) CreateOwner(ctx context.Context, arg CreateOwnerParams) (string, error) {
	row := q.db.QueryRow(ctx, createOwner, arg.OrganizerID, arg.Email)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listOrganizers = `-- name: ListOrganizers :many
SELECT o.id, o.name, o.slug, o.created_at, m.email AS owner_email
FROM organizers o
JOIN organizer_members m ON m.organizer_id = o.id AND m.role = 'owner'
ORDER BY o.id DESC
LIMIT $1
`

type ListOrganizersRow struct {
	ID         string
	Name       string
	Slug       string
	CreatedAt  time.Time
	OwnerEmail string
}

// Для админки платформы: все организаторы с email владельца, новые сверху.
func (q *Queries) ListOrganizers(ctx context.Context, pageSize int32) ([]ListOrganizersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizers, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizersRow{}
	for rows.Next() {
		var i ListOrganizersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
