// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package ticketdb

import (
	"context"
	"time"
)

const getOrderDelivery = `-- name: GetOrderDelivery :one
SELECT o.buyer_id, o.email, o.status, e.title, e.starts_at
FROM orders o JOIN events e ON e.id = o.event_id
WHERE o.id = $1
`

type GetOrderDeliveryRow struct {
	BuyerID  string
	Email    string
	Status   string
	Title    string
	StartsAt time.Time
}

func (q *Queries) GetOrderDelivery(ctx context.Context, id string) (GetOrderDeliveryRow, error) {
	row := q.db.QueryRow(ctx, getOrderDelivery, id)
	var i GetOrderDeliveryRow
	err := row.Scan(
		&i.BuyerID,
		&i.Email,
		&i.Status,
		&i.Title,
		&i.StartsAt,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT t.id, t.status, s.kind, s.section, s.row_label, s.seat_label,
       e.title, e.starts_at, e.ends_at, e.age_rating,
       v.name AS venue_name, v.address AS venue_address, v.timezone AS venue_timezone
FROM tickets t
JOIN event_seats s ON s.id = t.event_seat_id
JOIN events e ON e.id = t.event_id
JOIN venues v ON v.id = e.venue_id
WHERE t.id = $1
`

type GetTicketRow struct {
	ID            string
	Status        string
	Kind          string
	Section       string
	RowLabel      *string
	SeatLabel     string
	Title         string
	StartsAt      time.Time
	EndsAt        time.Time
	AgeRating     string
	VenueName     string
	VenueAddress  string
	VenueTimezone string
}

func (q *Queries) GetTicket(ctx context.Context, id string) (GetTicketRow, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i GetTicketRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Kind,
		&i.Section,
		&i.RowLabel,
		&i.SeatLabel,
		&i.Title,
		&i.StartsAt,
		&i.EndsAt,
		&i.AgeRating,
		&i.VenueName,
		&i.VenueAddress,
		&i.VenueTimezone,
	)
	return i, err
}

const issueTickets = `-- name: IssueTickets :many

INSERT INTO tickets (organizer_id, event_id, order_id, order_item_id, event_seat_id)
SELECT i.organizer_id, i.event_id, i.order_id, i.id, i.event_seat_id
FROM order_items i JOIN orders o ON o.id = i.order_id
WHERE i.order_id = $1 AND o.status = 'paid'
ON CONFLICT (order_item_id) DO NOTHING
RETURNING id
`

// Запросы модуля ticket (ADR 012). Сгенерировать: make sqlc
// Заказы, места и события принадлежат другим модулям: здесь их только читают.
// Билет на каждую позицию оплаченного заказа. Повтор ничего не добавит
// (order_item_id уникален). Второй действующий билет на место не вставится
// из-за tickets_one_active_per_seat_key — главный инвариант на уровне схемы.
func (q *Queries) IssueTickets(ctx context.Context, orderID string) ([]string, error) {
	rows, err := q.db.Query(ctx, issueTickets, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderTickets = `-- name: ListOrderTickets :many
SELECT t.id, t.status, s.kind, s.section, s.row_label, s.seat_label
FROM tickets t JOIN event_seats s ON s.id = t.event_seat_id
WHERE t.order_id = $1
ORDER BY s.section, s.row_label, s.seat_label
`

type ListOrderTicketsRow struct {
	ID        string
	Status    string
	Kind      string
	Section   string
	RowLabel  *string
	SeatLabel string
}

func (q *Queries) ListOrderTickets(ctx context.Context, orderID string) ([]ListOrderTicketsRow, error) {
	rows, err := q.db.Query(ctx, listOrderTickets, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderTicketsRow{}
	for rows.Next() {
		var i ListOrderTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Kind,
			&i.Section,
			&i.RowLabel,
			&i.SeatLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
