// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package ticketdb

import (
	"context"
	"time"
)

const createScannerLink = `-- name: CreateScannerLink :one

INSERT INTO scanner_links (organizer_id, event_id, name, token_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, event_id, name, created_at, revoked_at
`

type CreateScannerLinkParams struct {
	OrganizerID string
	EventID     string
	Name        string
	TokenHash   []byte
}

type CreateScannerLinkRow struct {
	ID        string
	EventID   string
	Name      string
	CreatedAt time.Time
	RevokedAt *time.Time
}

// Контроль входа (ADR 013).
func (q *Queries) CreateScannerLink(ctx context.Context, arg CreateScannerLinkParams) (CreateScannerLinkRow, error) {
	row := q.db.QueryRow(ctx, createScannerLink,
		arg.OrganizerID,
		arg.EventID,
		arg.Name,
		arg.TokenHash,
	)
	var i CreateScannerLinkRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const demoteAcceptedScan = `-- name: DemoteAcceptedScan :exec
UPDATE ticket_scans SET result = 'duplicate' WHERE ticket_id = $1 AND result = 'accepted'
`

func (q *Queries) DemoteAcceptedScan(ctx context.Context, ticketID string) error {
	_, err := q.db.Exec(ctx, demoteAcceptedScan, ticketID)
	return err
}

const exportTickets = `-- name: ExportTickets :many
SELECT t.id, s.section, s.row_label, s.seat_label, pc.name AS category, i.price_tiyn,
       t.status, t.order_id, o.email, t.issued_at, t.used_at
FROM tickets t
JOIN event_seats s ON s.id = t.event_seat_id
JOIN price_categories pc ON pc.id = s.price_category_id
JOIN order_items i ON i.id = t.order_item_id
JOIN orders o ON o.id = t.order_id
WHERE t.event_id = $1
ORDER BY s.section, s.row_label, s.seat_label, t.issued_at
`

type ExportTicketsRow struct {
	ID        string
	Section   string
	RowLabel  *string
	SeatLabel string
	Category  string
	PriceTiyn int64
	Status    string
	OrderID   string
	Email     string
	IssuedAt  time.Time
	UsedAt    *time.Time
}

func (q *Queries) ExportTickets(ctx context.Context, eventID string) ([]ExportTicketsRow, error) {
	rows, err := q.db.Query(ctx, exportTickets, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportTicketsRow{}
	for rows.Next() {
		var i ExportTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Section,
			&i.RowLabel,
			&i.SeatLabel,
			&i.Category,
			&i.PriceTiyn,
			&i.Status,
			&i.OrderID,
			&i.Email,
			&i.IssuedAt,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderDelivery = `-- name: GetOrderDelivery :one
SELECT o.buyer_id, o.email, o.status, e.title, e.starts_at
FROM orders o JOIN events e ON e.id = o.event_id
WHERE o.id = $1
`

type GetOrderDeliveryRow struct {
	BuyerID  string
	Email    string
	Status   string
	Title    string
	StartsAt time.Time
}

func (q *Queries) GetOrderDelivery(ctx context.Context, id string) (GetOrderDeliveryRow, error) {
	row := q.db.QueryRow(ctx, getOrderDelivery, id)
	var i GetOrderDeliveryRow
	err := row.Scan(
		&i.BuyerID,
		&i.Email,
		&i.Status,
		&i.Title,
		&i.StartsAt,
	)
	return i, err
}

const getRefundContext = `-- name: GetRefundContext :one

SELECT o.buyer_id, o.status, e.status AS event_status, e.starts_at, e.refund_deadline_hours
FROM orders o JOIN events e ON e.id = o.event_id
WHERE o.id = $1
`

type GetRefundContextRow struct {
	BuyerID             string
	Status              string
	EventStatus         string
	StartsAt            time.Time
	RefundDeadlineHours int32
}

// Возвраты (ADR 014).
func (q *Queries) GetRefundContext(ctx context.Context, orderID string) (GetRefundContextRow, error) {
	row := q.db.QueryRow(ctx, getRefundContext, orderID)
	var i GetRefundContextRow
	err := row.Scan(
		&i.BuyerID,
		&i.Status,
		&i.EventStatus,
		&i.StartsAt,
		&i.RefundDeadlineHours,
	)
	return i, err
}

const getScanByClient = `-- name: GetScanByClient :one
SELECT sc.result, sc.ticket_id, t.used_at, s.section, s.row_label, s.seat_label
FROM ticket_scans sc
JOIN tickets t ON t.id = sc.ticket_id
JOIN event_seats s ON s.id = t.event_seat_id
WHERE sc.scanner_link_id = $1 AND sc.client_scan_id = $2
`

type GetScanByClientParams struct {
	ScannerLinkID string
	ClientScanID  string
}

type GetScanByClientRow struct {
	Result    string
	TicketID  string
	UsedAt    *time.Time
	Section   string
	RowLabel  *string
	SeatLabel string
}

func (q *Queries) GetScanByClient(ctx context.Context, arg GetScanByClientParams) (GetScanByClientRow, error) {
	row := q.db.QueryRow(ctx, getScanByClient, arg.ScannerLinkID, arg.ClientScanID)
	var i GetScanByClientRow
	err := row.Scan(
		&i.Result,
		&i.TicketID,
		&i.UsedAt,
		&i.Section,
		&i.RowLabel,
		&i.SeatLabel,
	)
	return i, err
}

const getScannerByTokenHash = `-- name: GetScannerByTokenHash :one
SELECT l.id, l.organizer_id, l.event_id, l.name, l.revoked_at,
       e.title, e.starts_at, e.ends_at, v.name AS venue_name, v.timezone AS venue_timezone
FROM scanner_links l
JOIN events e ON e.id = l.event_id
JOIN venues v ON v.id = e.venue_id
WHERE l.token_hash = $1
`

type GetScannerByTokenHashRow struct {
	ID            string
	OrganizerID   string
	EventID       string
	Name          string
	RevokedAt     *time.Time
	Title         string
	StartsAt      time.Time
	EndsAt        time.Time
	VenueName     string
	VenueTimezone string
}

func (q *Queries) GetScannerByTokenHash(ctx context.Context, tokenHash []byte) (GetScannerByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getScannerByTokenHash, tokenHash)
	var i GetScannerByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.EventID,
		&i.Name,
		&i.RevokedAt,
		&i.Title,
		&i.StartsAt,
		&i.EndsAt,
		&i.VenueName,
		&i.VenueTimezone,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT t.id, t.status, s.kind, s.section, s.row_label, s.seat_label,
       e.title, e.starts_at, e.ends_at, e.age_rating,
       v.name AS venue_name, v.address AS venue_address, v.timezone AS venue_timezone
FROM tickets t
JOIN event_seats s ON s.id = t.event_seat_id
JOIN events e ON e.id = t.event_id
JOIN venues v ON v.id = e.venue_id
WHERE t.id = $1
`

type GetTicketRow struct {
	ID            string
	Status        string
	Kind          string
	Section       string
	RowLabel      *string
	SeatLabel     string
	Title         string
	StartsAt      time.Time
	EndsAt        time.Time
	AgeRating     string
	VenueName     string
	VenueAddress  string
	VenueTimezone string
}

func (q *Queries) GetTicket(ctx context.Context, id string) (GetTicketRow, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i GetTicketRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Kind,
		&i.Section,
		&i.RowLabel,
		&i.SeatLabel,
		&i.Title,
		&i.StartsAt,
		&i.EndsAt,
		&i.AgeRating,
		&i.VenueName,
		&i.VenueAddress,
		&i.VenueTimezone,
	)
	return i, err
}

const insertScan = `-- name: InsertScan :exec
INSERT INTO ticket_scans (organizer_id, ticket_id, device_id, scanned_at, result, scanner_link_id, client_scan_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertScanParams struct {
	OrganizerID   string
	TicketID      string
	DeviceID      string
	ScannedAt     time.Time
	Result        string
	ScannerLinkID string
	ClientScanID  string
}

func (q *Queries) InsertScan(ctx context.Context, arg InsertScanParams) error {
	_, err := q.db.Exec(ctx, insertScan,
		arg.OrganizerID,
		arg.TicketID,
		arg.DeviceID,
		arg.ScannedAt,
		arg.Result,
		arg.ScannerLinkID,
		arg.ClientScanID,
	)
	return err
}

const issueTickets = `-- name: IssueTickets :many

INSERT INTO tickets (organizer_id, event_id, order_id, order_item_id, event_seat_id)
SELECT i.organizer_id, i.event_id, i.order_id, i.id, i.event_seat_id
FROM order_items i JOIN orders o ON o.id = i.order_id
WHERE i.order_id = $1 AND o.status = 'paid'
ON CONFLICT (order_item_id) DO NOTHING
RETURNING id
`

// Запросы модуля ticket (ADR 012). Сгенерировать: make sqlc
// Заказы, места и события принадлежат другим модулям: здесь их только читают.
// Билет на каждую позицию оплаченного заказа. Повтор ничего не добавит
// (order_item_id уникален). Второй действующий билет на место не вставится
// из-за tickets_one_active_per_seat_key — главный инвариант на уровне схемы.
func (q *Queries) IssueTickets(ctx context.Context, orderID string) ([]string, error) {
	rows, err := q.db.Query(ctx, issueTickets, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderTickets = `-- name: ListOrderTickets :many
SELECT t.id, t.status, s.kind, s.section, s.row_label, s.seat_label
FROM tickets t JOIN event_seats s ON s.id = t.event_seat_id
WHERE t.order_id = $1
ORDER BY s.section, s.row_label, s.seat_label
`

type ListOrderTicketsRow struct {
	ID        string
	Status    string
	Kind      string
	Section   string
	RowLabel  *string
	SeatLabel string
}

func (q *Queries) ListOrderTickets(ctx context.Context, orderID string) ([]ListOrderTicketsRow, error) {
	rows, err := q.db.Query(ctx, listOrderTickets, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderTicketsRow{}
	for rows.Next() {
		var i ListOrderTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Kind,
			&i.Section,
			&i.RowLabel,
			&i.SeatLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScannerLinks = `-- name: ListScannerLinks :many
SELECT id, event_id, name, created_at, revoked_at FROM scanner_links
WHERE organizer_id = $1 AND event_id = $2
ORDER BY created_at
`

type ListScannerLinksParams struct {
	OrganizerID string
	EventID     string
}

type ListScannerLinksRow struct {
	ID        string
	EventID   string
	Name      string
	CreatedAt time.Time
	RevokedAt *time.Time
}

func (q *Queries) ListScannerLinks(ctx context.Context, arg ListScannerLinksParams) ([]ListScannerLinksRow, error) {
	rows, err := q.db.Query(ctx, listScannerLinks, arg.OrganizerID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScannerLinksRow{}
	for rows.Next() {
		var i ListScannerLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEventTicketsForCancel = `-- name: LockEventTicketsForCancel :many
SELECT t.id, t.order_id, t.status, i.price_tiyn
FROM tickets t JOIN order_items i ON i.id = t.order_item_id
WHERE t.event_id = $1 AND t.status IN ('issued', 'used')
ORDER BY t.order_id, t.id
FOR UPDATE OF t
`

type LockEventTicketsForCancelRow struct {
	ID        string
	OrderID   string
	Status    string
	PriceTiyn int64
}

// Все действующие билеты отменённого события.
func (q *Queries) LockEventTicketsForCancel(ctx context.Context, eventID string) ([]LockEventTicketsForCancelRow, error) {
	rows, err := q.db.Query(ctx, lockEventTicketsForCancel, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockEventTicketsForCancelRow{}
	for rows.Next() {
		var i LockEventTicketsForCancelRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Status,
			&i.PriceTiyn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrderTickets = `-- name: LockOrderTickets :many
SELECT t.id, t.status, i.price_tiyn
FROM tickets t JOIN order_items i ON i.id = t.order_item_id
WHERE t.order_id = $1 AND t.id = ANY($2::uuid[])
ORDER BY t.id
FOR UPDATE OF t
`

type LockOrderTicketsParams struct {
	OrderID string
	Ids     []string
}

type LockOrderTicketsRow struct {
	ID        string
	Status    string
	PriceTiyn int64
}

// Билеты заказа под блокировкой: сканирование и возврат одного билета
// выполняются по очереди.
func (q *Queries) LockOrderTickets(ctx context.Context, arg LockOrderTicketsParams) ([]LockOrderTicketsRow, error) {
	rows, err := q.db.Query(ctx, lockOrderTickets, arg.OrderID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockOrderTicketsRow{}
	for rows.Next() {
		var i LockOrderTicketsRow
		if err := rows.Scan(&i.ID, &i.Status, &i.PriceTiyn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTicketForScan = `-- name: LockTicketForScan :one
SELECT t.id, t.organizer_id, t.event_id, t.status, t.used_at, s.section, s.row_label, s.seat_label
FROM tickets t JOIN event_seats s ON s.id = t.event_seat_id
WHERE t.id = $1
FOR UPDATE OF t
`

type LockTicketForScanRow struct {
	ID          string
	OrganizerID string
	EventID     string
	Status      string
	UsedAt      *time.Time
	Section     string
	RowLabel    *string
	SeatLabel   string
}

func (q *Queries) LockTicketForScan(ctx context.Context, id string) (LockTicketForScanRow, error) {
	row := q.db.QueryRow(ctx, lockTicketForScan, id)
	var i LockTicketForScanRow
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.EventID,
		&i.Status,
		&i.UsedAt,
		&i.Section,
		&i.RowLabel,
		&i.SeatLabel,
	)
	return i, err
}

const manifestTickets = `-- name: ManifestTickets :many
SELECT t.id, t.status, s.section, s.row_label, s.seat_label
FROM tickets t JOIN event_seats s ON s.id = t.event_seat_id
WHERE t.event_id = $1
ORDER BY t.id
`

type ManifestTicketsRow struct {
	ID        string
	Status    string
	Section   string
	RowLabel  *string
	SeatLabel string
}

// Все билеты события для проверки без сети: id, статус и место.
func (q *Queries) ManifestTickets(ctx context.Context, eventID string) ([]ManifestTicketsRow, error) {
	rows, err := q.db.Query(ctx, manifestTickets, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManifestTicketsRow{}
	for rows.Next() {
		var i ManifestTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Section,
			&i.RowLabel,
			&i.SeatLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTicketUsed = `-- name: MarkTicketUsed :exec
UPDATE tickets SET status = 'used', used_at = $1::timestamptz WHERE id = $2 AND status = 'issued'
`

type MarkTicketUsedParams struct {
	UsedAt time.Time
	ID     string
}

func (q *Queries) MarkTicketUsed(ctx context.Context, arg MarkTicketUsedParams) error {
	_, err := q.db.Exec(ctx, markTicketUsed, arg.UsedAt, arg.ID)
	return err
}

const moveTicketUsedAt = `-- name: MoveTicketUsedAt :exec
UPDATE tickets SET used_at = $1::timestamptz WHERE id = $2 AND status = 'used'
`

type MoveTicketUsedAtParams struct {
	UsedAt time.Time
	ID     string
}

func (q *Queries) MoveTicketUsedAt(ctx context.Context, arg MoveTicketUsedAtParams) error {
	_, err := q.db.Exec(ctx, moveTicketUsedAt, arg.UsedAt, arg.ID)
	return err
}

const reportCategories = `-- name: ReportCategories :many
SELECT pc.name, pc.price_tiyn,
       count(s.id)::int AS capacity,
       count(t.id)::int AS sold,
       coalesce(sum(i.price_tiyn), 0)::bigint AS revenue
FROM price_categories pc
LEFT JOIN event_seats s ON s.price_category_id = pc.id
LEFT JOIN tickets t ON t.event_seat_id = s.id AND t.status IN ('issued', 'used')
LEFT JOIN order_items i ON i.id = t.order_item_id
WHERE pc.event_id = $1
GROUP BY pc.id, pc.name, pc.price_tiyn
ORDER BY pc.price_tiyn DESC, pc.name
`

type ReportCategoriesRow struct {
	Name      string
	PriceTiyn int64
	Capacity  int32
	Sold      int32
	Revenue   int64
}

// Продажи по ценовым категориям: действующие билеты по цене на момент покупки.
func (q *Queries) ReportCategories(ctx context.Context, eventID string) ([]ReportCategoriesRow, error) {
	rows, err := q.db.Query(ctx, reportCategories, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportCategoriesRow{}
	for rows.Next() {
		var i ReportCategoriesRow
		if err := rows.Scan(
			&i.Name,
			&i.PriceTiyn,
			&i.Capacity,
			&i.Sold,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportEvent = `-- name: ReportEvent :one

SELECT id, title, status, admission, starts_at FROM events WHERE organizer_id = $1 AND id = $2
`

type ReportEventParams struct {
	OrganizerID string
	ID          string
}

type ReportEventRow struct {
	ID        string
	Title     string
	Status    string
	Admission string
	StartsAt  time.Time
}

// Отчёты организатора (ADR 014).
func (q *Queries) ReportEvent(ctx context.Context, arg ReportEventParams) (ReportEventRow, error) {
	row := q.db.QueryRow(ctx, reportEvent, arg.OrganizerID, arg.ID)
	var i ReportEventRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Admission,
		&i.StartsAt,
	)
	return i, err
}

const reportMoney = `-- name: ReportMoney :one
SELECT
    (SELECT coalesce(sum(total_tiyn), 0) FROM orders o WHERE o.event_id = $1 AND o.paid_at IS NOT NULL)::bigint AS gross,
    (SELECT count(*) FROM orders o WHERE o.event_id = $1 AND o.paid_at IS NOT NULL)::int AS paid_orders,
    (SELECT coalesce(sum(r.amount_tiyn), 0) FROM refunds r JOIN orders o ON o.id = r.order_id
      WHERE o.event_id = $1 AND r.status = 'succeeded' AND o.paid_at IS NOT NULL)::bigint AS refunded
`

type ReportMoneyRow struct {
	Gross      int64
	PaidOrders int32
	Refunded   int64
}

func (q *Queries) ReportMoney(ctx context.Context, eventID string) (ReportMoneyRow, error) {
	row := q.db.QueryRow(ctx, reportMoney, eventID)
	var i ReportMoneyRow
	err := row.Scan(&i.Gross, &i.PaidOrders, &i.Refunded)
	return i, err
}

const reportSeats = `-- name: ReportSeats :one
SELECT count(*)::int AS capacity,
       count(*) FILTER (WHERE status = 'sold')::int AS sold,
       count(*) FILTER (WHERE status = 'held' AND hold_expires_at > $1::timestamptz)::int AS held
FROM event_seats WHERE event_id = $2
`

type ReportSeatsParams struct {
	Now     time.Time
	EventID string
}

type ReportSeatsRow struct {
	Capacity int32
	Sold     int32
	Held     int32
}

func (q *Queries) ReportSeats(ctx context.Context, arg ReportSeatsParams) (ReportSeatsRow, error) {
	row := q.db.QueryRow(ctx, reportSeats, arg.Now, arg.EventID)
	var i ReportSeatsRow
	err := row.Scan(&i.Capacity, &i.Sold, &i.Held)
	return i, err
}

const reportTickets = `-- name: ReportTickets :one
SELECT count(*) FILTER (WHERE status IN ('issued', 'used'))::int AS active,
       count(*) FILTER (WHERE status = 'used')::int AS used,
       count(*) FILTER (WHERE status = 'revoked')::int AS revoked
FROM tickets WHERE event_id = $1
`

type ReportTicketsRow struct {
	Active  int32
	Used    int32
	Revoked int32
}

func (q *Queries) ReportTickets(ctx context.Context, eventID string) (ReportTicketsRow, error) {
	row := q.db.QueryRow(ctx, reportTickets, eventID)
	var i ReportTicketsRow
	err := row.Scan(&i.Active, &i.Used, &i.Revoked)
	return i, err
}

const revokeScannerLink = `-- name: RevokeScannerLink :execrows
UPDATE scanner_links SET revoked_at = now()
WHERE organizer_id = $1 AND id = $2 AND revoked_at IS NULL
`

type RevokeScannerLinkParams struct {
	OrganizerID string
	ID          string
}

func (q *Queries) RevokeScannerLink(ctx context.Context, arg RevokeScannerLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeScannerLink, arg.OrganizerID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeTickets = `-- name: RevokeTickets :exec
UPDATE tickets SET status = 'revoked', revoked_at = now()
WHERE id = ANY($1::uuid[]) AND status = 'issued'
`

func (q *Queries) RevokeTickets(ctx context.Context, ids []string) error {
	_, err := q.db.Exec(ctx, revokeTickets, ids)
	return err
}

const scannerLinkExists = `-- name: ScannerLinkExists :one
SELECT EXISTS (SELECT 1 FROM scanner_links WHERE organizer_id = $1 AND id = $2)
`

type ScannerLinkExistsParams struct {
	OrganizerID string
	ID          string
}

func (q *Queries) ScannerLinkExists(ctx context.Context, arg ScannerLinkExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, scannerLinkExists, arg.OrganizerID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
