// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package bookingdb

import (
	"context"
	"time"
)

const countGeneralAvailable = `-- name: CountGeneralAvailable :many
SELECT section, count(*) FILTER (WHERE status = 'available')::int AS available
FROM event_seats
WHERE event_id = $1 AND kind = 'general'
GROUP BY section
ORDER BY section
`

type CountGeneralAvailableRow struct {
	Section   string
	Available int32
}

func (q *Queries) CountGeneralAvailable(ctx context.Context, eventID string) ([]CountGeneralAvailableRow, error) {
	rows, err := q.db.Query(ctx, countGeneralAvailable, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountGeneralAvailableRow{}
	for rows.Next() {
		var i CountGeneralAvailableRow
		if err := rows.Scan(&i.Section, &i.Available); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOrderItems = `-- name: CountOrderItems :one
SELECT count(*)::int FROM order_items WHERE order_id = $1
`

func (q *Queries) CountOrderItems(ctx context.Context, orderID string) (int32, error) {
	row := q.db.QueryRow(ctx, countOrderItems, orderID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const expireDueOrders = `-- name: ExpireDueOrders :many
UPDATE orders SET status = 'expired', updated_at = now()
WHERE id IN (
    SELECT o.id FROM orders o
    WHERE o.status = 'pending' AND o.expires_at <= $1::timestamptz
    ORDER BY o.expires_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id
`

type ExpireDueOrdersParams struct {
	Now   time.Time
	Batch int32
}

// Пачка просроченных заказов. SKIP LOCKED: несколько воркеров не мешают друг другу.
func (q *Queries) ExpireDueOrders(ctx context.Context, arg ExpireDueOrdersParams) ([]string, error) {
	rows, err := q.db.Query(ctx, expireDueOrders, arg.Now, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookableEvent = `-- name: GetBookableEvent :one

SELECT id, organizer_id, status, starts_at, sales_start_at, sales_end_at, max_tickets_per_buyer
FROM events WHERE id = $1
`

type GetBookableEventRow struct {
	ID                 string
	OrganizerID        string
	Status             string
	StartsAt           time.Time
	SalesStartAt       *time.Time
	SalesEndAt         *time.Time
	MaxTicketsPerBuyer int32
}

// Запросы модуля booking (ADR 011). Сгенерировать: make sqlc
func (q *Queries) GetBookableEvent(ctx context.Context, id string) (GetBookableEventRow, error) {
	row := q.db.QueryRow(ctx, getBookableEvent, id)
	var i GetBookableEventRow
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Status,
		&i.StartsAt,
		&i.SalesStartAt,
		&i.SalesEndAt,
		&i.MaxTicketsPerBuyer,
	)
	return i, err
}

const getBuyerOrder = `-- name: GetBuyerOrder :one
SELECT id, organizer_id, event_id, buyer_id, status, email, total_tiyn, currency, expires_at, paid_at, created_at, updated_at FROM orders WHERE id = $1 AND buyer_id = $2
`

type GetBuyerOrderParams struct {
	ID      string
	BuyerID string
}

func (q *Queries) GetBuyerOrder(ctx context.Context, arg GetBuyerOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getBuyerOrder, arg.ID, arg.BuyerID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.EventID,
		&i.BuyerID,
		&i.Status,
		&i.Email,
		&i.TotalTiyn,
		&i.Currency,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedEventStatus = `-- name: GetPublishedEventStatus :one
SELECT status FROM events WHERE id = $1
`

func (q *Queries) GetPublishedEventStatus(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getPublishedEventStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const holdGeneral = `-- name: HoldGeneral :many
WITH picked AS (
    SELECT g.id FROM event_seats g
    WHERE g.event_id = $3 AND g.kind = 'general' AND g.section = $4 AND g.status = 'available'
    ORDER BY g.id
    LIMIT $5
    FOR UPDATE SKIP LOCKED
)
UPDATE event_seats s
SET status = 'held', hold_order_id = $1::uuid, hold_expires_at = $2::timestamptz
FROM picked, price_categories p
WHERE s.id = picked.id AND p.id = s.price_category_id
RETURNING s.id, s.section, s.row_label, s.seat_label, p.price_tiyn
`

type HoldGeneralParams struct {
	OrderID   string
	ExpiresAt time.Time
	EventID   string
	Section   string
	Quantity  int32
}

type HoldGeneralRow struct {
	ID        string
	Section   string
	RowLabel  *string
	SeatLabel string
	PriceTiyn int64
}

// Холд любых свободных виртуальных мест входной зоны. SKIP LOCKED: параллельные
// покупатели берут разные строки и не ждут друг друга.
func (q *Queries) HoldGeneral(ctx context.Context, arg HoldGeneralParams) ([]HoldGeneralRow, error) {
	rows, err := q.db.Query(ctx, holdGeneral,
		arg.OrderID,
		arg.ExpiresAt,
		arg.EventID,
		arg.Section,
		arg.Quantity,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HoldGeneralRow{}
	for rows.Next() {
		var i HoldGeneralRow
		if err := rows.Scan(
			&i.ID,
			&i.Section,
			&i.RowLabel,
			&i.SeatLabel,
			&i.PriceTiyn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const holdSeats = `-- name: HoldSeats :many
WITH target AS (
    SELECT s.id FROM event_seats s
    WHERE s.event_id = $4 AND s.kind = 'seat'
      AND (s.section, s.row_label, s.seat_label) IN (
          SELECT unnest($5::text[]), unnest($6::text[]), unnest($7::text[]))
    ORDER BY s.id
    FOR UPDATE
)
UPDATE event_seats s
SET status = 'held', hold_order_id = $1::uuid, hold_expires_at = $2::timestamptz
FROM target, price_categories p
WHERE s.id = target.id AND p.id = s.price_category_id
  AND (s.status = 'available' OR (s.status = 'held' AND s.hold_expires_at <= $3::timestamptz))
RETURNING s.id, s.section, s.row_label, s.seat_label, p.price_tiyn
`

type HoldSeatsParams struct {
	OrderID    string
	ExpiresAt  time.Time
	Now        time.Time
	EventID    string
	Sections   []string
	Rows       []string
	SeatLabels []string
}

type HoldSeatsRow struct {
	ID        string
	Section   string
	RowLabel  *string
	SeatLabel string
	PriceTiyn int64
}

// Холд мест с рядом по позициям. Строки блокируются в порядке id, чтобы
// параллельные заказы с пересекающимися местами не взаимоблокировались;
// условие на статус проверяется уже после получения блокировки, поэтому
// место достаётся ровно одному заказу. Истёкший холд считается свободным.
func (q *Queries) HoldSeats(ctx context.Context, arg HoldSeatsParams) ([]HoldSeatsRow, error) {
	rows, err := q.db.Query(ctx, holdSeats,
		arg.OrderID,
		arg.ExpiresAt,
		arg.Now,
		arg.EventID,
		arg.Sections,
		arg.Rows,
		arg.SeatLabels,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HoldSeatsRow{}
	for rows.Next() {
		var i HoldSeatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Section,
			&i.RowLabel,
			&i.SeatLabel,
			&i.PriceTiyn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (id, organizer_id, event_id, buyer_id, email, total_tiyn, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organizer_id, event_id, buyer_id, status, email, total_tiyn, currency, expires_at, paid_at, created_at, updated_at
`

type InsertOrderParams struct {
	ID          string
	OrganizerID string
	EventID     string
	BuyerID     string
	Email       string
	TotalTiyn   int64
	ExpiresAt   time.Time
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.ID,
		arg.OrganizerID,
		arg.EventID,
		arg.BuyerID,
		arg.Email,
		arg.TotalTiyn,
		arg.ExpiresAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.EventID,
		&i.BuyerID,
		&i.Status,
		&i.Email,
		&i.TotalTiyn,
		&i.Currency,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrderItems = `-- name: InsertOrderItems :exec
INSERT INTO order_items (organizer_id, event_id, order_id, event_seat_id, price_tiyn)
SELECT $1::uuid, $2::uuid, $3::uuid, unnest($4::uuid[]), unnest($5::bigint[])
`

type InsertOrderItemsParams struct {
	OrganizerID string
	EventID     string
	OrderID     string
	SeatIds     []string
	Prices      []int64
}

func (q *Queries) InsertOrderItems(ctx context.Context, arg InsertOrderItemsParams) error {
	_, err := q.db.Exec(ctx, insertOrderItems,
		arg.OrganizerID,
		arg.EventID,
		arg.OrderID,
		arg.SeatIds,
		arg.Prices,
	)
	return err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT i.event_seat_id, s.kind, s.section, s.row_label, s.seat_label, i.price_tiyn
FROM order_items i JOIN event_seats s ON s.id = i.event_seat_id
WHERE i.order_id = $1
ORDER BY s.section, s.row_label, s.seat_label
`

type ListOrderItemsRow struct {
	EventSeatID string
	Kind        string
	Section     string
	RowLabel    *string
	SeatLabel   string
	PriceTiyn   int64
}

func (q *Queries) ListOrderItems(ctx context.Context, orderID string) ([]ListOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderItemsRow{}
	for rows.Next() {
		var i ListOrderItemsRow
		if err := rows.Scan(
			&i.EventSeatID,
			&i.Kind,
			&i.Section,
			&i.RowLabel,
			&i.SeatLabel,
			&i.PriceTiyn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTakenSeats = `-- name: ListTakenSeats :many
SELECT section, row_label, seat_label FROM event_seats
WHERE event_id = $1 AND kind = 'seat'
  AND (status = 'sold' OR (status = 'held' AND hold_expires_at > $2::timestamptz))
ORDER BY section, row_label, seat_label
`

type ListTakenSeatsParams struct {
	EventID string
	Now     time.Time
}

type ListTakenSeatsRow struct {
	Section   string
	RowLabel  *string
	SeatLabel string
}

// Занятые места с рядом: проданные и под действующим холдом.
func (q *Queries) ListTakenSeats(ctx context.Context, arg ListTakenSeatsParams) ([]ListTakenSeatsRow, error) {
	rows, err := q.db.Query(ctx, listTakenSeats, arg.EventID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTakenSeatsRow{}
	for rows.Next() {
		var i ListTakenSeatsRow
		if err := rows.Scan(&i.Section, &i.RowLabel, &i.SeatLabel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBuyerOrder = `-- name: LockBuyerOrder :one
SELECT id, organizer_id, event_id, buyer_id, status, email, total_tiyn, currency, expires_at, paid_at, created_at, updated_at FROM orders WHERE id = $1 AND buyer_id = $2 FOR UPDATE
`

type LockBuyerOrderParams struct {
	ID      string
	BuyerID string
}

func (q *Queries) LockBuyerOrder(ctx context.Context, arg LockBuyerOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, lockBuyerOrder, arg.ID, arg.BuyerID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.EventID,
		&i.BuyerID,
		&i.Status,
		&i.Email,
		&i.TotalTiyn,
		&i.Currency,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockOrder = `-- name: LockOrder :one
SELECT id, organizer_id, event_id, buyer_id, status, email, total_tiyn, currency, expires_at, paid_at, created_at, updated_at FROM orders WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockOrder(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, lockOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.EventID,
		&i.BuyerID,
		&i.Status,
		&i.Email,
		&i.TotalTiyn,
		&i.Currency,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockPendingOrder = `-- name: LockPendingOrder :one
SELECT id, expires_at FROM orders
WHERE buyer_id = $1 AND event_id = $2 AND status = 'pending'
FOR UPDATE
`

type LockPendingOrderParams struct {
	BuyerID string
	EventID string
}

type LockPendingOrderRow struct {
	ID        string
	ExpiresAt time.Time
}

// Активная корзина покупателя на событие, под блокировкой: её заменяет новый заказ.
func (q *Queries) LockPendingOrder(ctx context.Context, arg LockPendingOrderParams) (LockPendingOrderRow, error) {
	row := q.db.QueryRow(ctx, lockPendingOrder, arg.BuyerID, arg.EventID)
	var i LockPendingOrderRow
	err := row.Scan(&i.ID, &i.ExpiresAt)
	return i, err
}

const markOrderPaid = `-- name: MarkOrderPaid :one
UPDATE orders SET status = 'paid', paid_at = $1::timestamptz, updated_at = now()
WHERE id = $2 AND status = 'pending'
RETURNING id, organizer_id, event_id, buyer_id, status, email, total_tiyn, currency, expires_at, paid_at, created_at, updated_at
`

type MarkOrderPaidParams struct {
	PaidAt time.Time
	ID     string
}

func (q *Queries) MarkOrderPaid(ctx context.Context, arg MarkOrderPaidParams) (Order, error) {
	row := q.db.QueryRow(ctx, markOrderPaid, arg.PaidAt, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.EventID,
		&i.BuyerID,
		&i.Status,
		&i.Email,
		&i.TotalTiyn,
		&i.Currency,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseOrderSeats = `-- name: ReleaseOrderSeats :many
UPDATE event_seats
SET status = 'available', hold_order_id = NULL, hold_expires_at = NULL
WHERE hold_order_id = $1::uuid AND status = 'held'
RETURNING id, kind, section, row_label, seat_label
`

type ReleaseOrderSeatsRow struct {
	ID        string
	Kind      string
	Section   string
	RowLabel  *string
	SeatLabel string
}

// Освобождает места, которые ещё держит заказ. Место, которое после
// истечения холда уже взял другой заказ, не трогается.
func (q *Queries) ReleaseOrderSeats(ctx context.Context, orderID string) ([]ReleaseOrderSeatsRow, error) {
	rows, err := q.db.Query(ctx, releaseOrderSeats, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReleaseOrderSeatsRow{}
	for rows.Next() {
		var i ReleaseOrderSeatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Section,
			&i.RowLabel,
			&i.SeatLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseSeatsOfOrders = `-- name: ReleaseSeatsOfOrders :exec
UPDATE event_seats
SET status = 'available', hold_order_id = NULL, hold_expires_at = NULL
WHERE hold_order_id = ANY($1::uuid[]) AND status = 'held'
`

func (q *Queries) ReleaseSeatsOfOrders(ctx context.Context, orderIds []string) error {
	_, err := q.db.Exec(ctx, releaseSeatsOfOrders, orderIds)
	return err
}

const sellOrderSeats = `-- name: SellOrderSeats :many
UPDATE event_seats
SET status = 'sold', hold_order_id = NULL, hold_expires_at = NULL
WHERE hold_order_id = $1::uuid AND status = 'held'
RETURNING id
`

// Продаёт места, которые всё ещё держит заказ (даже если срок холда уже
// вышел, но место никто не перехватил).
func (q *Queries) SellOrderSeats(ctx context.Context, orderID string) ([]string, error) {
	rows, err := q.db.Query(ctx, sellOrderSeats, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrderStatus = `-- name: SetOrderStatus :one
UPDATE orders SET status = $1, updated_at = now()
WHERE id = $2 AND status = 'pending'
RETURNING id, organizer_id, event_id, buyer_id, status, email, total_tiyn, currency, expires_at, paid_at, created_at, updated_at
`

type SetOrderStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, setOrderStatus, arg.Status, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.EventID,
		&i.BuyerID,
		&i.Status,
		&i.Email,
		&i.TotalTiyn,
		&i.Currency,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setOrderTotal = `-- name: SetOrderTotal :one
UPDATE orders SET total_tiyn = $1, updated_at = now() WHERE id = $2 RETURNING id, organizer_id, event_id, buyer_id, status, email, total_tiyn, currency, expires_at, paid_at, created_at, updated_at
`

type SetOrderTotalParams struct {
	TotalTiyn int64
	ID        string
}

func (q *Queries) SetOrderTotal(ctx context.Context, arg SetOrderTotalParams) (Order, error) {
	row := q.db.QueryRow(ctx, setOrderTotal, arg.TotalTiyn, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.EventID,
		&i.BuyerID,
		&i.Status,
		&i.Email,
		&i.TotalTiyn,
		&i.Currency,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
