// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package bookingdb

import (
	"context"
	"net/netip"
	"time"
)

const countBuyerTickets = `-- name: CountBuyerTickets :one
SELECT count(*)::int FROM order_items i
JOIN orders o ON o.id = i.order_id
LEFT JOIN tickets t ON t.order_item_id = i.id
WHERE o.buyer_id = $1 AND o.event_id = $2
  AND o.status IN ('paid', 'partially_refunded')
  AND (t.id IS NULL OR t.status <> 'revoked')
`

type CountBuyerTicketsParams struct {
	BuyerID string
	EventID string
}

// Сколько билетов покупатель уже купил на событие: места оплаченных заказов,
// кроме возвращённых билетов.
func (q *Queries) CountBuyerTickets(ctx context.Context, arg CountBuyerTicketsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countBuyerTickets, arg.BuyerID, arg.EventID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countGeneralAvailable = `-- name: CountGeneralAvailable :many
SELECT section, count(*) FILTER (WHERE status = 'available')::int AS available
FROM event_seats
WHERE event_id = $1 AND kind = 'general'
GROUP BY section
ORDER BY section
`

type CountGeneralAvailableRow struct {
	Section   string
	Available int32
}

func (q *Queries) CountGeneralAvailable(ctx context.Context, eventID string) ([]CountGeneralAvailableRow, error) {
	rows, err := q.db.Query(ctx, countGeneralAvailable, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountGeneralAvailableRow{}
	for rows.Next() {
		var i CountGeneralAvailableRow
		if err := rows.Scan(&i.Section, &i.Available); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countIPTickets = `-- name: CountIPTickets :one
SELECT count(*)::int FROM order_items i
JOIN orders o ON o.id = i.order_id
LEFT JOIN tickets t ON t.order_item_id = i.id
WHERE o.event_id = $1 AND o.client_ip = $2::inet
  AND (
      (o.status IN ('paid', 'partially_refunded') AND (t.id IS NULL OR t.status <> 'revoked'))
      OR (o.status = 'pending' AND o.expires_at > $3 AND o.buyer_id <> $4)
  )
`

type CountIPTicketsParams struct {
	EventID  string
	ClientIp netip.Addr
	Now      time.Time
	BuyerID  string
}

// Сколько билетов на событие уже взято с этого IP-адреса (ADR 020): места
// оплаченных заказов без возвращённых и действующие корзины других
// покупателей. Своя корзина не считается: новый заказ её заменит.
func (q *Queries) CountIPTickets(ctx context.Context, arg CountIPTicketsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countIPTickets,
		arg.EventID,
		arg.ClientIp,
		arg.Now,
		arg.BuyerID,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countOrderItems = `-- name: CountOrderItems :one
SELECT count(*)::int FROM order_items WHERE order_id = $1
`

func (q *Queries) CountOrderItems(ctx context.Context, orderID string) (int32, error) {
	row := q.db.QueryRow(ctx, countOrderItems, orderID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countSeatAvailability = `-- name: CountSeatAvailability :many
SELECT section, count(*)::int AS total,
       count(*) FILTER (WHERE status = 'available'
                           OR (status = 'held' AND hold_expires_at <= $1::timestamptz))::int AS available
FROM event_seats
WHERE event_id = $2 AND kind = 'seat'
GROUP BY section
ORDER BY section
`

type CountSeatAvailabilityParams struct {
	Now     time.Time
	EventID string
}

type CountSeatAvailabilityRow struct {
	Section   string
	Total     int32
	Available int32
}

// Свободные и все места с рядом по секторам — для плана площадки.
func (q *Queries) CountSeatAvailability(ctx context.Context, arg CountSeatAvailabilityParams) ([]CountSeatAvailabilityRow, error) {
	rows, err := q.db.Query(ctx, countSeatAvailability, arg.Now, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSeatAvailabilityRow{}
	for rows.Next() {
		var i CountSeatAvailabilityRow
		if err := rows.Scan(&i.Section, &i.Total, &i.Available); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSectionAvailability = `-- name: CountSectionAvailability :many
SELECT section, count(*)::int AS total,
       count(*) FILTER (WHERE status = 'available'
                           OR (status = 'held' AND hold_expires_at <= $1::timestamptz))::int AS available
FROM event_seats
WHERE event_id = $2 AND kind = 'seat' AND section = $3
GROUP BY section
`

type CountSectionAvailabilityParams struct {
	Now     time.Time
	EventID string
	Section string
}

type CountSectionAvailabilityRow struct {
	Section   string
	Total     int32
	Available int32
}

// То же для одного сектора: открытому сектору не нужна сводка по всему
// стадиону (ADR 026).
func (q *Queries) CountSectionAvailability(ctx context.Context, arg CountSectionAvailabilityParams) ([]CountSectionAvailabilityRow, error) {
	rows, err := q.db.Query(ctx, countSectionAvailability, arg.Now, arg.EventID, arg.Section)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSectionAvailabilityRow{}
	for rows.Next() {
		var i CountSectionAvailabilityRow
		if err := rows.Scan(&i.Section, &i.Total, &i.Available); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnrefundedTickets = `-- name: CountUnrefundedTickets :one
SELECT count(*)::int FROM tickets t
JOIN order_items i ON i.id = t.order_item_id
WHERE t.order_id = $1
  AND NOT (
      (t.status = 'revoked' AND i.price_tiyn = 0)
      OR EXISTS (
          SELECT 1 FROM refund_items ri JOIN refunds r ON r.id = ri.refund_id
          WHERE ri.ticket_id = t.id AND r.status = 'succeeded'))
`

// Билеты заказа, деньги за которые ещё не вернулись: возврат успешен или
// билет бесплатный и аннулирован.
func (q *Queries) CountUnrefundedTickets(ctx context.Context, orderID string) (int32, error) {
	row := q.db.QueryRow(ctx, countUnrefundedTickets, orderID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const expireDueOrders = `-- name: ExpireDueOrders :many
UPDATE orders SET status = 'expired', updated_at = now()
WHERE id IN (
    SELECT o.id FROM orders o
    WHERE o.status = 'pending' AND o.expires_at <= $1::timestamptz
    ORDER BY o.expires_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id
`

type ExpireDueOrdersParams struct {
	Now   time.Time
	Batch int32
}

// Пачка просроченных заказов. SKIP LOCKED: несколько воркеров не мешают друг другу.
func (q *Queries) ExpireDueOrders(ctx context.Context, arg ExpireDueOrdersParams) ([]string, error) {
	rows, err := q.db.Query(ctx, expireDueOrders, arg.Now, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookableEvent = `-- name: GetBookableEvent :one

SELECT id, organizer_id, status, admission, starts_at, sales_start_at, sales_end_at, max_tickets_per_buyer, waiting_room
FROM events WHERE id = $1
`

type GetBookableEventRow struct {
	ID                 string
	OrganizerID        string
	Status             string
	Admission          string
	StartsAt           time.Time
	SalesStartAt       *time.Time
	SalesEndAt         *time.Time
	MaxTicketsPerBuyer int32
	WaitingRoom        bool
}

// Запросы модуля booking (ADR 011). Сгенерировать: make sqlc
func (q *Queries) GetBookableEvent(ctx context.Context, id string) (GetBookableEventRow, error) {
	row := q.db.QueryRow(ctx, getBookableEvent, id)
	var i GetBookableEventRow
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Status,
		&i.Admission,
		&i.StartsAt,
		&i.SalesStartAt,
		&i.SalesEndAt,
		&i.MaxTicketsPerBuyer,
		&i.WaitingRoom,
	)
	return i, err
}

const getBuyerOrder = `-- name: GetBuyerOrder :one
SELECT id, organizer_id, event_id, buyer_id, status, email, total_tiyn, currency, expires_at, paid_at, created_at, updated_at, client_ip FROM orders WHERE id = $1 AND buyer_id = $2
`

type GetBuyerOrderParams struct {
	ID      string
	BuyerID string
}

func (q *Queries) GetBuyerOrder(ctx context.Context, arg GetBuyerOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getBuyerOrder, arg.ID, arg.BuyerID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.EventID,
		&i.BuyerID,
		&i.Status,
		&i.Email,
		&i.TotalTiyn,
		&i.Currency,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientIp,
	)
	return i, err
}

const getEventStatus = `-- name: GetEventStatus :one
SELECT status FROM events WHERE id = $1
`

func (q *Queries) GetEventStatus(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getEventStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getPublishedEventStatus = `-- name: GetPublishedEventStatus :one
SELECT status, sales_start_at, waiting_room FROM events WHERE id = $1
`

type GetPublishedEventStatusRow struct {
	Status       string
	SalesStartAt *time.Time
	WaitingRoom  bool
}

func (q *Queries) GetPublishedEventStatus(ctx context.Context, id string) (GetPublishedEventStatusRow, error) {
	row := q.db.QueryRow(ctx, getPublishedEventStatus, id)
	var i GetPublishedEventStatusRow
	err := row.Scan(&i.Status, &i.SalesStartAt, &i.WaitingRoom)
	return i, err
}

const holdGeneral = `-- name: HoldGeneral :many
WITH picked AS (
    SELECT g.id FROM event_seats g
    WHERE g.event_id = $3 AND g.kind = 'general' AND g.section = $4 AND g.status = 'available'
    ORDER BY g.id
    LIMIT $5
    FOR UPDATE SKIP LOCKED
)
UPDATE event_seats s
SET status = 'held', hold_order_id = $1::uuid, hold_expires_at = $2::timestamptz
FROM picked, price_categories p
WHERE s.id = picked.id AND p.id = s.price_category_id
RETURNING s.id, s.section, s.row_label, s.seat_label, p.price_tiyn
`

type HoldGeneralParams struct {
	OrderID   string
	ExpiresAt time.Time
	EventID   string
	Section   string
	Quantity  int32
}

type HoldGeneralRow struct {
	ID        string
	Section   string
	RowLabel  *string
	SeatLabel string
	PriceTiyn int64
}

// Холд любых свободных виртуальных мест входной зоны. SKIP LOCKED: параллельные
// покупатели берут разные строки и не ждут друг друга.
func (q *Queries) HoldGeneral(ctx context.Context, arg HoldGeneralParams) ([]HoldGeneralRow, error) {
	rows, err := q.db.Query(ctx, holdGeneral,
		arg.OrderID,
		arg.ExpiresAt,
		arg.EventID,
		arg.Section,
		arg.Quantity,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HoldGeneralRow{}
	for rows.Next() {
		var i HoldGeneralRow
		if err := rows.Scan(
			&i.ID,
			&i.Section,
			&i.RowLabel,
			&i.SeatLabel,
			&i.PriceTiyn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const holdSeats = `-- name: HoldSeats :many
WITH target AS (
    SELECT s.id FROM event_seats s
    WHERE s.event_id = $4 AND s.kind = 'seat'
      AND (s.section, s.row_label, s.seat_label) IN (
          SELECT unnest($5::text[]), unnest($6::text[]), unnest($7::text[]))
    ORDER BY s.id
    FOR UPDATE
)
UPDATE event_seats s
SET status = 'held', hold_order_id = $1::uuid, hold_expires_at = $2::timestamptz
FROM target, price_categories p
WHERE s.id = target.id AND p.id = s.price_category_id
  AND (s.status = 'available' OR (s.status = 'held' AND s.hold_expires_at <= $3::timestamptz))
RETURNING s.id, s.section, s.row_label, s.seat_label, p.price_tiyn
`

type HoldSeatsParams struct {
	OrderID    string
	ExpiresAt  time.Time
	Now        time.Time
	EventID    string
	Sections   []string
	Rows       []string
	SeatLabels []string
}

type HoldSeatsRow struct {
	ID        string
	Section   string
	RowLabel  *string
	SeatLabel string
	PriceTiyn int64
}

// Холд мест с рядом по позициям. Строки блокируются в порядке id, чтобы
// параллельные заказы с пересекающимися местами не взаимоблокировались;
// условие на статус проверяется уже после получения блокировки, поэтому
// место достаётся ровно одному заказу. Истёкший холд считается свободным.
func (q *Queries) HoldSeats(ctx context.Context, arg HoldSeatsParams) ([]HoldSeatsRow, error) {
	rows, err := q.db.Query(ctx, holdSeats,
		arg.OrderID,
		arg.ExpiresAt,
		arg.Now,
		arg.EventID,
		arg.Sections,
		arg.Rows,
		arg.SeatLabels,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HoldSeatsRow{}
	for rows.Next() {
		var i HoldSeatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Section,
			&i.RowLabel,
			&i.SeatLabel,
			&i.PriceTiyn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const holdSeatsIfVersion = `-- name: HoldSeatsIfVersion :many
UPDATE event_seats s
SET status = 'held', hold_order_id = $1::uuid, hold_expires_at = $2::timestamptz
FROM (SELECT unnest($3::uuid[]) AS id, unnest($4::integer[]) AS version) v
WHERE s.id = v.id AND s.version = v.version
RETURNING s.id
`

type HoldSeatsIfVersionParams struct {
	OrderID   string
	ExpiresAt time.Time
	Ids       []string
	Versions  []int32
}

// Холд, только если версия строки не изменилась с момента чтения. Версию
// увеличивает триггер. Вернулось меньше строк — кто-то успел раньше:
// транзакция откатывается и попытка повторяется.
func (q *Queries) HoldSeatsIfVersion(ctx context.Context, arg HoldSeatsIfVersionParams) ([]string, error) {
	rows, err := q.db.Query(ctx, holdSeatsIfVersion,
		arg.OrderID,
		arg.ExpiresAt,
		arg.Ids,
		arg.Versions,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (id, organizer_id, event_id, buyer_id, email, total_tiyn, expires_at, client_ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8::inet)
RETURNING id, organizer_id, event_id, buyer_id, status, email, total_tiyn, currency, expires_at, paid_at, created_at, updated_at, client_ip
`

type InsertOrderParams struct {
	ID          string
	OrganizerID string
	EventID     string
	BuyerID     string
	Email       string
	TotalTiyn   int64
	ExpiresAt   time.Time
	ClientIp    *netip.Addr
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.ID,
		arg.OrganizerID,
		arg.EventID,
		arg.BuyerID,
		arg.Email,
		arg.TotalTiyn,
		arg.ExpiresAt,
		arg.ClientIp,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.EventID,
		&i.BuyerID,
		&i.Status,
		&i.Email,
		&i.TotalTiyn,
		&i.Currency,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientIp,
	)
	return i, err
}

const insertOrderItems = `-- name: InsertOrderItems :exec
INSERT INTO order_items (organizer_id, event_id, order_id, event_seat_id, price_tiyn, fee_tiyn)
SELECT $1::uuid, $2::uuid, $3::uuid, unnest($4::uuid[]), unnest($5::bigint[]), unnest($6::bigint[])
`

type InsertOrderItemsParams struct {
	OrganizerID string
	EventID     string
	OrderID     string
	SeatIds     []string
	Prices      []int64
	Fees        []int64
}

func (q *Queries) InsertOrderItems(ctx context.Context, arg InsertOrderItemsParams) error {
	_, err := q.db.Exec(ctx, insertOrderItems,
		arg.OrganizerID,
		arg.EventID,
		arg.OrderID,
		arg.SeatIds,
		arg.Prices,
		arg.Fees,
	)
	return err
}

const listBuyerOrders = `-- name: ListBuyerOrders :many
SELECT o.id, o.status, o.total_tiyn, o.created_at, o.expires_at,
       e.id AS event_id, e.slug AS event_slug, e.title AS event_title, e.starts_at AS event_starts_at,
       org.slug AS organizer_slug, v.name AS venue_name, v.timezone AS venue_timezone,
       (SELECT count(*) FROM order_items i WHERE i.order_id = o.id)::int AS items
FROM orders o
JOIN events e ON e.id = o.event_id
JOIN organizers org ON org.id = o.organizer_id
JOIN venues v ON v.id = e.venue_id
WHERE o.buyer_id = $1 AND o.status NOT IN ('cancelled', 'expired')
ORDER BY o.created_at DESC
LIMIT 100
`

type ListBuyerOrdersRow struct {
	ID            string
	Status        string
	TotalTiyn     int64
	CreatedAt     time.Time
	ExpiresAt     time.Time
	EventID       string
	EventSlug     string
	EventTitle    string
	EventStartsAt time.Time
	OrganizerSlug string
	VenueName     string
	VenueTimezone string
	Items         int32
}

// Заказы покупателя для раздела «Мои билеты»: действующие и завершённые,
// без отменённых и истёкших корзин.
func (q *Queries) ListBuyerOrders(ctx context.Context, buyerID string) ([]ListBuyerOrdersRow, error) {
	rows, err := q.db.Query(ctx, listBuyerOrders, buyerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBuyerOrdersRow{}
	for rows.Next() {
		var i ListBuyerOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.TotalTiyn,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.EventID,
			&i.EventSlug,
			&i.EventTitle,
			&i.EventStartsAt,
			&i.OrganizerSlug,
			&i.VenueName,
			&i.VenueTimezone,
			&i.Items,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT i.event_seat_id, s.kind, s.section, s.row_label, s.seat_label, i.price_tiyn, i.fee_tiyn
FROM order_items i JOIN event_seats s ON s.id = i.event_seat_id
WHERE i.order_id = $1
ORDER BY s.section, s.row_label, s.seat_label
`

type ListOrderItemsRow struct {
	EventSeatID string
	Kind        string
	Section     string
	RowLabel    *string
	SeatLabel   string
	PriceTiyn   int64
	FeeTiyn     int64
}

func (q *Queries) ListOrderItems(ctx context.Context, orderID string) ([]ListOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderItemsRow{}
	for rows.Next() {
		var i ListOrderItemsRow
		if err := rows.Scan(
			&i.EventSeatID,
			&i.Kind,
			&i.Section,
			&i.RowLabel,
			&i.SeatLabel,
			&i.PriceTiyn,
			&i.FeeTiyn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTakenSeats = `-- name: ListTakenSeats :many
SELECT section, row_label, seat_label FROM event_seats
WHERE event_id = $1 AND kind = 'seat'
  AND (status = 'sold' OR (status = 'held' AND hold_expires_at > $2::timestamptz))
ORDER BY section, row_label, seat_label
`

type ListTakenSeatsParams struct {
	EventID string
	Now     time.Time
}

type ListTakenSeatsRow struct {
	Section   string
	RowLabel  *string
	SeatLabel string
}

// Занятые места с рядом: проданные и под действующим холдом.
func (q *Queries) ListTakenSeats(ctx context.Context, arg ListTakenSeatsParams) ([]ListTakenSeatsRow, error) {
	rows, err := q.db.Query(ctx, listTakenSeats, arg.EventID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTakenSeatsRow{}
	for rows.Next() {
		var i ListTakenSeatsRow
		if err := rows.Scan(&i.Section, &i.RowLabel, &i.SeatLabel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTakenSeatsInSection = `-- name: ListTakenSeatsInSection :many
SELECT section, row_label, seat_label FROM event_seats
WHERE event_id = $1 AND kind = 'seat' AND section = $2
  AND (status = 'sold' OR (status = 'held' AND hold_expires_at > $3::timestamptz))
ORDER BY row_label, seat_label
`

type ListTakenSeatsInSectionParams struct {
	EventID string
	Section string
	Now     time.Time
}

type ListTakenSeatsInSectionRow struct {
	Section   string
	RowLabel  *string
	SeatLabel string
}

// Занятые места одного сектора: схема стадиона показывает места только
// выбранного сектора (ADR 024).
func (q *Queries) ListTakenSeatsInSection(ctx context.Context, arg ListTakenSeatsInSectionParams) ([]ListTakenSeatsInSectionRow, error) {
	rows, err := q.db.Query(ctx, listTakenSeatsInSection, arg.EventID, arg.Section, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTakenSeatsInSectionRow{}
	for rows.Next() {
		var i ListTakenSeatsInSectionRow
		if err := rows.Scan(&i.Section, &i.RowLabel, &i.SeatLabel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBuyerOrder = `-- name: LockBuyerOrder :one
SELECT id, organizer_id, event_id, buyer_id, status, email, total_tiyn, currency, expires_at, paid_at, created_at, updated_at, client_ip FROM orders WHERE id = $1 AND buyer_id = $2 FOR UPDATE
`

type LockBuyerOrderParams struct {
	ID      string
	BuyerID string
}

func (q *Queries) LockBuyerOrder(ctx context.Context, arg LockBuyerOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, lockBuyerOrder, arg.ID, arg.BuyerID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.EventID,
		&i.BuyerID,
		&i.Status,
		&i.Email,
		&i.TotalTiyn,
		&i.Currency,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientIp,
	)
	return i, err
}

const lockOrder = `-- name: LockOrder :one
SELECT id, organizer_id, event_id, buyer_id, status, email, total_tiyn, currency, expires_at, paid_at, created_at, updated_at, client_ip FROM orders WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockOrder(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, lockOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.EventID,
		&i.BuyerID,
		&i.Status,
		&i.Email,
		&i.TotalTiyn,
		&i.Currency,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientIp,
	)
	return i, err
}

const lockPendingOrder = `-- name: LockPendingOrder :one
SELECT id, expires_at FROM orders
WHERE buyer_id = $1 AND event_id = $2 AND status = 'pending'
FOR UPDATE
`

type LockPendingOrderParams struct {
	BuyerID string
	EventID string
}

type LockPendingOrderRow struct {
	ID        string
	ExpiresAt time.Time
}

// Активная корзина покупателя на событие, под блокировкой: её заменяет новый заказ.
func (q *Queries) LockPendingOrder(ctx context.Context, arg LockPendingOrderParams) (LockPendingOrderRow, error) {
	row := q.db.QueryRow(ctx, lockPendingOrder, arg.BuyerID, arg.EventID)
	var i LockPendingOrderRow
	err := row.Scan(&i.ID, &i.ExpiresAt)
	return i, err
}

const markOrderPaid = `-- name: MarkOrderPaid :one
UPDATE orders SET status = 'paid', paid_at = $1::timestamptz, updated_at = now()
WHERE id = $2 AND status = 'pending'
RETURNING id, organizer_id, event_id, buyer_id, status, email, total_tiyn, currency, expires_at, paid_at, created_at, updated_at, client_ip
`

type MarkOrderPaidParams struct {
	PaidAt time.Time
	ID     string
}

func (q *Queries) MarkOrderPaid(ctx context.Context, arg MarkOrderPaidParams) (Order, error) {
	row := q.db.QueryRow(ctx, markOrderPaid, arg.PaidAt, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.EventID,
		&i.BuyerID,
		&i.Status,
		&i.Email,
		&i.TotalTiyn,
		&i.Currency,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientIp,
	)
	return i, err
}

const readSeatsForHold = `-- name: ReadSeatsForHold :many
SELECT s.id, s.section, s.row_label, s.seat_label, s.status, s.hold_expires_at, s.version, p.price_tiyn
FROM event_seats s
JOIN price_categories p ON p.id = s.price_category_id
WHERE s.event_id = $1 AND s.kind = 'seat'
  AND (s.section, s.row_label, s.seat_label) IN (
      SELECT unnest($2::text[]), unnest($3::text[]), unnest($4::text[]))
`

type ReadSeatsForHoldParams struct {
	EventID    string
	Sections   []string
	Rows       []string
	SeatLabels []string
}

type ReadSeatsForHoldRow struct {
	ID            string
	Section       string
	RowLabel      *string
	SeatLabel     string
	Status        string
	HoldExpiresAt *time.Time
	Version       int32
	PriceTiyn     int64
}

// Оптимистичная стратегия (ADR 017): места читаются без блокировки вместе с
// версией строки; решение «свободно ли» принимает приложение.
func (q *Queries) ReadSeatsForHold(ctx context.Context, arg ReadSeatsForHoldParams) ([]ReadSeatsForHoldRow, error) {
	rows, err := q.db.Query(ctx, readSeatsForHold,
		arg.EventID,
		arg.Sections,
		arg.Rows,
		arg.SeatLabels,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadSeatsForHoldRow{}
	for rows.Next() {
		var i ReadSeatsForHoldRow
		if err := rows.Scan(
			&i.ID,
			&i.Section,
			&i.RowLabel,
			&i.SeatLabel,
			&i.Status,
			&i.HoldExpiresAt,
			&i.Version,
			&i.PriceTiyn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseOrderSeats = `-- name: ReleaseOrderSeats :many
UPDATE event_seats
SET status = 'available', hold_order_id = NULL, hold_expires_at = NULL
WHERE hold_order_id = $1::uuid AND status = 'held'
RETURNING id, kind, section, row_label, seat_label
`

type ReleaseOrderSeatsRow struct {
	ID        string
	Kind      string
	Section   string
	RowLabel  *string
	SeatLabel string
}

// Освобождает места, которые ещё держит заказ. Место, которое после
// истечения холда уже взял другой заказ, не трогается.
func (q *Queries) ReleaseOrderSeats(ctx context.Context, orderID string) ([]ReleaseOrderSeatsRow, error) {
	rows, err := q.db.Query(ctx, releaseOrderSeats, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReleaseOrderSeatsRow{}
	for rows.Next() {
		var i ReleaseOrderSeatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Section,
			&i.RowLabel,
			&i.SeatLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseRefundedSeats = `-- name: ReleaseRefundedSeats :many
UPDATE event_seats s SET status = 'available', hold_order_id = NULL, hold_expires_at = NULL
FROM tickets t
WHERE t.id = ANY($1::uuid[]) AND s.id = t.event_seat_id AND s.status = 'sold'
RETURNING s.id, s.kind, s.section, s.row_label, s.seat_label
`

type ReleaseRefundedSeatsRow struct {
	ID        string
	Kind      string
	Section   string
	RowLabel  *string
	SeatLabel string
}

// Места возвращённых билетов снова продаются. Возвращает места, чтобы
// снять их ключи холдов в Redis.
func (q *Queries) ReleaseRefundedSeats(ctx context.Context, ticketIds []string) ([]ReleaseRefundedSeatsRow, error) {
	rows, err := q.db.Query(ctx, releaseRefundedSeats, ticketIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReleaseRefundedSeatsRow{}
	for rows.Next() {
		var i ReleaseRefundedSeatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Section,
			&i.RowLabel,
			&i.SeatLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseSeatsOfOrders = `-- name: ReleaseSeatsOfOrders :exec
UPDATE event_seats
SET status = 'available', hold_order_id = NULL, hold_expires_at = NULL
WHERE hold_order_id = ANY($1::uuid[]) AND status = 'held'
`

func (q *Queries) ReleaseSeatsOfOrders(ctx context.Context, orderIds []string) error {
	_, err := q.db.Exec(ctx, releaseSeatsOfOrders, orderIds)
	return err
}

const sellOrderSeats = `-- name: SellOrderSeats :many
UPDATE event_seats
SET status = 'sold', hold_order_id = NULL, hold_expires_at = NULL
WHERE hold_order_id = $1::uuid AND status = 'held'
RETURNING id
`

// Продаёт места, которые всё ещё держит заказ (даже если срок холда уже
// вышел, но место никто не перехватил).
func (q *Queries) SellOrderSeats(ctx context.Context, orderID string) ([]string, error) {
	rows, err := q.db.Query(ctx, sellOrderSeats, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrderRefundStatus = `-- name: SetOrderRefundStatus :exec
UPDATE orders SET status = $1, updated_at = now()
WHERE id = $2 AND status IN ('paid', 'partially_refunded')
`

type SetOrderRefundStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) SetOrderRefundStatus(ctx context.Context, arg SetOrderRefundStatusParams) error {
	_, err := q.db.Exec(ctx, setOrderRefundStatus, arg.Status, arg.ID)
	return err
}

const setOrderStatus = `-- name: SetOrderStatus :one
UPDATE orders SET status = $1, updated_at = now()
WHERE id = $2 AND status = 'pending'
RETURNING id, organizer_id, event_id, buyer_id, status, email, total_tiyn, currency, expires_at, paid_at, created_at, updated_at, client_ip
`

type SetOrderStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, setOrderStatus, arg.Status, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.EventID,
		&i.BuyerID,
		&i.Status,
		&i.Email,
		&i.TotalTiyn,
		&i.Currency,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientIp,
	)
	return i, err
}

const setOrderTotal = `-- name: SetOrderTotal :one
UPDATE orders SET total_tiyn = $1, updated_at = now() WHERE id = $2 RETURNING id, organizer_id, event_id, buyer_id, status, email, total_tiyn, currency, expires_at, paid_at, created_at, updated_at, client_ip
`

type SetOrderTotalParams struct {
	TotalTiyn int64
	ID        string
}

func (q *Queries) SetOrderTotal(ctx context.Context, arg SetOrderTotalParams) (Order, error) {
	row := q.db.QueryRow(ctx, setOrderTotal, arg.TotalTiyn, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.EventID,
		&i.BuyerID,
		&i.Status,
		&i.Email,
		&i.TotalTiyn,
		&i.Currency,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientIp,
	)
	return i, err
}
