// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package outboxdb

import (
	"context"
	"time"
)

const deletePublished = `-- name: DeletePublished :execrows
DELETE FROM outbox WHERE published_at < $1::timestamptz
`

func (q *Queries) DeletePublished(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deletePublished, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insert = `-- name: Insert :exec
INSERT INTO outbox (topic, payload) VALUES ($1, $2)
`

type InsertParams struct {
	Topic   string
	Payload []byte
}

func (q *Queries) Insert(ctx context.Context, arg InsertParams) error {
	_, err := q.db.Exec(ctx, insert, arg.Topic, arg.Payload)
	return err
}

const lockUnpublished = `-- name: LockUnpublished :many
SELECT id, topic, payload FROM outbox
WHERE published_at IS NULL
ORDER BY id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type LockUnpublishedRow struct {
	ID      string
	Topic   string
	Payload []byte
}

// SKIP LOCKED: несколько релеев не публикуют одно сообщение одновременно.
func (q *Queries) LockUnpublished(ctx context.Context, batch int32) ([]LockUnpublishedRow, error) {
	rows, err := q.db.Query(ctx, lockUnpublished, batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockUnpublishedRow{}
	for rows.Next() {
		var i LockUnpublishedRow
		if err := rows.Scan(&i.ID, &i.Topic, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPublished = `-- name: MarkPublished :exec
UPDATE outbox SET published_at = now() WHERE id = ANY($1::uuid[])
`

func (q *Queries) MarkPublished(ctx context.Context, ids []string) error {
	_, err := q.db.Exec(ctx, markPublished, ids)
	return err
}
