// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitydb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Buyer struct {
	ID        string
	Phone     string
	CreatedAt pgtype.Timestamptz
}

type Event struct {
	ID                  string
	OrganizerID         string
	VenueID             string
	SeatMapID           string
	Slug                string
	Title               string
	Description         string
	Status              string
	StartsAt            pgtype.Timestamptz
	EndsAt              pgtype.Timestamptz
	SalesStartAt        pgtype.Timestamptz
	SalesEndAt          pgtype.Timestamptz
	MaxTicketsPerBuyer  int32
	RefundDeadlineHours int32
	PublishedAt         pgtype.Timestamptz
	CancelledAt         pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type EventSeat struct {
	ID              string
	OrganizerID     string
	EventID         string
	PriceCategoryID string
	Kind            string
	Section         string
	RowLabel        pgtype.Text
	SeatLabel       string
	Status          string
	HoldOrderID     pgtype.UUID
	HoldExpiresAt   pgtype.Timestamptz
	Version         int32
}

type IdempotencyKey struct {
	Scope          string
	Key            string
	RequestHash    []byte
	ResponseStatus pgtype.Int4
	ResponseBody   []byte
	CreatedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
}

type Order struct {
	ID          string
	OrganizerID string
	EventID     string
	BuyerID     string
	Status      string
	Email       string
	TotalTiyn   int64
	Currency    string
	ExpiresAt   pgtype.Timestamptz
	PaidAt      pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type OrderItem struct {
	ID          string
	OrganizerID string
	EventID     string
	OrderID     string
	EventSeatID string
	PriceTiyn   int64
}

type Organizer struct {
	ID        string
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type OrganizerMember struct {
	ID          string
	OrganizerID string
	Email       string
	Role        string
	CreatedAt   pgtype.Timestamptz
}

type Payment struct {
	ID                string
	OrganizerID       string
	OrderID           string
	Status            string
	AmountTiyn        int64
	Currency          string
	Provider          string
	ProviderPaymentID pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type PaymentWebhookEvent struct {
	Provider        string
	ProviderEventID string
	Payload         []byte
	ReceivedAt      pgtype.Timestamptz
	ProcessedAt     pgtype.Timestamptz
}

type PriceCategory struct {
	ID          string
	OrganizerID string
	EventID     string
	Name        string
	PriceTiyn   int64
	Currency    string
	CreatedAt   pgtype.Timestamptz
}

type Refund struct {
	ID               string
	OrganizerID      string
	PaymentID        string
	OrderID          string
	Status           string
	AmountTiyn       int64
	Reason           string
	ProviderRefundID pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type RefundItem struct {
	RefundID    string
	TicketID    string
	OrganizerID string
	OrderID     string
}

type SeatMap struct {
	ID          string
	OrganizerID string
	VenueID     string
	Name        string
	Layout      []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Ticket struct {
	ID          string
	OrganizerID string
	EventID     string
	OrderID     string
	OrderItemID string
	EventSeatID string
	Status      string
	IssuedAt    pgtype.Timestamptz
	UsedAt      pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

type TicketScan struct {
	ID          string
	OrganizerID string
	TicketID    string
	DeviceID    string
	ScannedAt   pgtype.Timestamptz
	ReceivedAt  pgtype.Timestamptz
	Result      string
}

type Venue struct {
	ID          string
	OrganizerID string
	Name        string
	Address     string
	Timezone    string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
