// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitydb

import (
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Buyer struct {
	ID        string
	Phone     string
	CreatedAt time.Time
}

type Event struct {
	ID                  string
	OrganizerID         string
	VenueID             string
	SeatMapID           *string
	Slug                string
	Title               string
	Description         string
	Status              string
	StartsAt            time.Time
	EndsAt              time.Time
	SalesStartAt        *time.Time
	SalesEndAt          *time.Time
	MaxTicketsPerBuyer  int32
	RefundDeadlineHours int32
	PublishedAt         *time.Time
	CancelledAt         *time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
	AgeRating           string
	CoverImageKey       *string
	CoverVideoKey       *string
	Admission           string
}

type EventSeat struct {
	ID              string
	OrganizerID     string
	EventID         string
	PriceCategoryID string
	Kind            string
	Section         string
	RowLabel        *string
	SeatLabel       string
	Status          string
	HoldOrderID     *string
	HoldExpiresAt   *time.Time
	Version         int32
}

type EventSectionPrice struct {
	OrganizerID     string
	EventID         string
	Section         string
	PriceCategoryID string
}

type IdempotencyKey struct {
	Scope               string
	Key                 string
	RequestHash         []byte
	ResponseStatus      pgtype.Int4
	ResponseBody        []byte
	CreatedAt           time.Time
	CompletedAt         *time.Time
	ResponseContentType *string
}

type Order struct {
	ID          string
	OrganizerID string
	EventID     string
	BuyerID     string
	Status      string
	Email       string
	TotalTiyn   int64
	Currency    string
	ExpiresAt   time.Time
	PaidAt      *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ClientIp    *netip.Addr
}

type OrderItem struct {
	ID          string
	OrganizerID string
	EventID     string
	OrderID     string
	EventSeatID string
	PriceTiyn   int64
	FeeTiyn     int64
}

type Organizer struct {
	ID        string
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OrganizerMember struct {
	ID          string
	OrganizerID string
	Email       string
	Role        string
	CreatedAt   time.Time
}

type Outbox struct {
	ID          string
	Topic       string
	Payload     []byte
	CreatedAt   time.Time
	PublishedAt *time.Time
}

type Payment struct {
	ID                string
	OrganizerID       string
	OrderID           string
	Status            string
	AmountTiyn        int64
	Currency          string
	Provider          string
	ProviderPaymentID *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	PaymentUrl        *string
}

type PaymentWebhookEvent struct {
	Provider        string
	ProviderEventID string
	Payload         []byte
	ReceivedAt      time.Time
	ProcessedAt     *time.Time
}

type PriceCategory struct {
	ID          string
	OrganizerID string
	EventID     string
	Name        string
	PriceTiyn   int64
	Currency    string
	CreatedAt   time.Time
}

type Refund struct {
	ID               string
	OrganizerID      string
	PaymentID        string
	OrderID          string
	Status           string
	AmountTiyn       int64
	Reason           string
	ProviderRefundID *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	RequestID        *string
}

type RefundItem struct {
	RefundID    string
	TicketID    string
	OrganizerID string
	OrderID     string
}

type ScannerLink struct {
	ID          string
	OrganizerID string
	EventID     string
	Name        string
	TokenHash   []byte
	CreatedAt   time.Time
	RevokedAt   *time.Time
}

type SeatMap struct {
	ID          string
	OrganizerID string
	VenueID     string
	Name        string
	Layout      []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Ticket struct {
	ID          string
	OrganizerID string
	EventID     string
	OrderID     string
	OrderItemID string
	EventSeatID string
	Status      string
	IssuedAt    time.Time
	UsedAt      *time.Time
	RevokedAt   *time.Time
}

type TicketScan struct {
	ID            string
	OrganizerID   string
	TicketID      string
	DeviceID      string
	ScannedAt     time.Time
	ReceivedAt    time.Time
	Result        string
	ScannerLinkID string
	ClientScanID  string
}

type Venue struct {
	ID          string
	OrganizerID string
	Name        string
	Address     string
	Timezone    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Latitude    *float64
	Longitude   *float64
}
