// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package identitydb

import (
	"context"
)

const getOwnerByEmail = `-- name: GetOwnerByEmail :one
SELECT id, organizer_id FROM organizer_members
WHERE email = $1 AND role = 'owner'
`

type GetOwnerByEmailRow struct {
	ID          string
	OrganizerID string
}

func (q *Queries) GetOwnerByEmail(ctx context.Context, email string) (GetOwnerByEmailRow, error) {
	row := q.db.QueryRow(ctx, getOwnerByEmail, email)
	var i GetOwnerByEmailRow
	err := row.Scan(&i.ID, &i.OrganizerID)
	return i, err
}

const upsertBuyerByPhone = `-- name: UpsertBuyerByPhone :one
INSERT INTO buyers (phone) VALUES ($1)
ON CONFLICT (phone) DO UPDATE SET phone = EXCLUDED.phone
RETURNING id
`

// Покупатель создаётся при первом успешном входе.
func (q *Queries) UpsertBuyerByPhone(ctx context.Context, phone string) (string, error) {
	row := q.db.QueryRow(ctx, upsertBuyerByPhone, phone)
	var id string
	err := row.Scan(&id)
	return id, err
}
