// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package paymentdb

import (
	"context"
	"time"
)

const getActivePayment = `-- name: GetActivePayment :one
SELECT id, organizer_id, order_id, status, amount_tiyn, currency, provider, provider_payment_id, created_at, updated_at, payment_url FROM payments WHERE order_id = $1 AND status IN ('created', 'pending')
`

func (q *Queries) GetActivePayment(ctx context.Context, orderID string) (Payment, error) {
	row := q.db.QueryRow(ctx, getActivePayment, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.OrderID,
		&i.Status,
		&i.AmountTiyn,
		&i.Currency,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentUrl,
	)
	return i, err
}

const getPayableOrder = `-- name: GetPayableOrder :one

SELECT o.id, o.organizer_id, o.status, o.total_tiyn, o.currency, o.expires_at, e.title AS event_title
FROM orders o JOIN events e ON e.id = o.event_id
WHERE o.id = $1 AND o.buyer_id = $2
`

type GetPayableOrderParams struct {
	ID      string
	BuyerID string
}

type GetPayableOrderRow struct {
	ID          string
	OrganizerID string
	Status      string
	TotalTiyn   int64
	Currency    string
	ExpiresAt   time.Time
	EventTitle  string
}

// Запросы модуля payment (ADR 012). Сгенерировать: make sqlc
// Заказы и события принадлежат другим модулям: здесь их только читают.
func (q *Queries) GetPayableOrder(ctx context.Context, arg GetPayableOrderParams) (GetPayableOrderRow, error) {
	row := q.db.QueryRow(ctx, getPayableOrder, arg.ID, arg.BuyerID)
	var i GetPayableOrderRow
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Status,
		&i.TotalTiyn,
		&i.Currency,
		&i.ExpiresAt,
		&i.EventTitle,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, organizer_id, order_id, status, amount_tiyn, currency, provider, provider_payment_id, created_at, updated_at, payment_url FROM payments WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.OrderID,
		&i.Status,
		&i.AmountTiyn,
		&i.Currency,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentUrl,
	)
	return i, err
}

const getRefund = `-- name: GetRefund :one
SELECT id, organizer_id, payment_id, order_id, status, amount_tiyn, reason, provider_refund_id, created_at, updated_at FROM refunds WHERE payment_id = $1 AND reason = $2
`

type GetRefundParams struct {
	PaymentID string
	Reason    string
}

func (q *Queries) GetRefund(ctx context.Context, arg GetRefundParams) (Refund, error) {
	row := q.db.QueryRow(ctx, getRefund, arg.PaymentID, arg.Reason)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.PaymentID,
		&i.OrderID,
		&i.Status,
		&i.AmountTiyn,
		&i.Reason,
		&i.ProviderRefundID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasSucceededPayment = `-- name: HasSucceededPayment :one
SELECT EXISTS (SELECT 1 FROM payments WHERE order_id = $1 AND status = 'succeeded')
`

func (q *Queries) HasSucceededPayment(ctx context.Context, orderID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasSucceededPayment, orderID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO payments (organizer_id, order_id, amount_tiyn, currency, provider)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organizer_id, order_id, status, amount_tiyn, currency, provider, provider_payment_id, created_at, updated_at, payment_url
`

type InsertPaymentParams struct {
	OrganizerID string
	OrderID     string
	AmountTiyn  int64
	Currency    string
	Provider    string
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, insertPayment,
		arg.OrganizerID,
		arg.OrderID,
		arg.AmountTiyn,
		arg.Currency,
		arg.Provider,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.OrderID,
		&i.Status,
		&i.AmountTiyn,
		&i.Currency,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentUrl,
	)
	return i, err
}

const insertRefund = `-- name: InsertRefund :one
INSERT INTO refunds (organizer_id, payment_id, order_id, amount_tiyn, reason)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
RETURNING id, organizer_id, payment_id, order_id, status, amount_tiyn, reason, provider_refund_id, created_at, updated_at
`

type InsertRefundParams struct {
	OrganizerID string
	PaymentID   string
	OrderID     string
	AmountTiyn  int64
	Reason      string
}

func (q *Queries) InsertRefund(ctx context.Context, arg InsertRefundParams) (Refund, error) {
	row := q.db.QueryRow(ctx, insertRefund,
		arg.OrganizerID,
		arg.PaymentID,
		arg.OrderID,
		arg.AmountTiyn,
		arg.Reason,
	)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.PaymentID,
		&i.OrderID,
		&i.Status,
		&i.AmountTiyn,
		&i.Reason,
		&i.ProviderRefundID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWebhookEvent = `-- name: InsertWebhookEvent :one
INSERT INTO payment_webhook_events (provider, provider_event_id, payload)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
RETURNING provider_event_id
`

type InsertWebhookEventParams struct {
	Provider        string
	ProviderEventID string
	Payload         []byte
}

// Повторная доставка того же уведомления не вставит строку: ErrNoRows.
func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (string, error) {
	row := q.db.QueryRow(ctx, insertWebhookEvent, arg.Provider, arg.ProviderEventID, arg.Payload)
	var provider_event_id string
	err := row.Scan(&provider_event_id)
	return provider_event_id, err
}

const lockPayment = `-- name: LockPayment :one
SELECT id, organizer_id, order_id, status, amount_tiyn, currency, provider, provider_payment_id, created_at, updated_at, payment_url FROM payments WHERE id = $1 AND provider = $2 FOR UPDATE
`

type LockPaymentParams struct {
	ID       string
	Provider string
}

func (q *Queries) LockPayment(ctx context.Context, arg LockPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, lockPayment, arg.ID, arg.Provider)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.OrderID,
		&i.Status,
		&i.AmountTiyn,
		&i.Currency,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentUrl,
	)
	return i, err
}

const markWebhookProcessed = `-- name: MarkWebhookProcessed :exec
UPDATE payment_webhook_events SET processed_at = now()
WHERE provider = $1 AND provider_event_id = $2
`

type MarkWebhookProcessedParams struct {
	Provider        string
	ProviderEventID string
}

func (q *Queries) MarkWebhookProcessed(ctx context.Context, arg MarkWebhookProcessedParams) error {
	_, err := q.db.Exec(ctx, markWebhookProcessed, arg.Provider, arg.ProviderEventID)
	return err
}

const setPaymentFailed = `-- name: SetPaymentFailed :exec
UPDATE payments SET status = 'failed', updated_at = now()
WHERE id = $1 AND status IN ('created', 'pending')
`

func (q *Queries) SetPaymentFailed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setPaymentFailed, id)
	return err
}

const setPaymentPending = `-- name: SetPaymentPending :one
UPDATE payments
SET status = 'pending', provider_payment_id = $1, payment_url = $2, updated_at = now()
WHERE id = $3 AND status IN ('created', 'pending')
RETURNING id, organizer_id, order_id, status, amount_tiyn, currency, provider, provider_payment_id, created_at, updated_at, payment_url
`

type SetPaymentPendingParams struct {
	ProviderPaymentID *string
	PaymentUrl        *string
	ID                string
}

func (q *Queries) SetPaymentPending(ctx context.Context, arg SetPaymentPendingParams) (Payment, error) {
	row := q.db.QueryRow(ctx, setPaymentPending, arg.ProviderPaymentID, arg.PaymentUrl, arg.ID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.OrderID,
		&i.Status,
		&i.AmountTiyn,
		&i.Currency,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentUrl,
	)
	return i, err
}

const setPaymentResult = `-- name: SetPaymentResult :one
UPDATE payments
SET status = $1, provider_payment_id = coalesce(provider_payment_id, $2::text), updated_at = now()
WHERE id = $3 AND status IN ('created', 'pending')
RETURNING id, organizer_id, order_id, status, amount_tiyn, currency, provider, provider_payment_id, created_at, updated_at, payment_url
`

type SetPaymentResultParams struct {
	Status            string
	ProviderPaymentID string
	ID                string
}

func (q *Queries) SetPaymentResult(ctx context.Context, arg SetPaymentResultParams) (Payment, error) {
	row := q.db.QueryRow(ctx, setPaymentResult, arg.Status, arg.ProviderPaymentID, arg.ID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.OrderID,
		&i.Status,
		&i.AmountTiyn,
		&i.Currency,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentUrl,
	)
	return i, err
}

const setRefundFailed = `-- name: SetRefundFailed :exec
UPDATE refunds SET status = 'failed', updated_at = now() WHERE id = $1
`

func (q *Queries) SetRefundFailed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setRefundFailed, id)
	return err
}

const setRefundPending = `-- name: SetRefundPending :exec
UPDATE refunds SET status = 'pending', updated_at = now()
WHERE id = $1 AND status IN ('requested', 'pending')
`

func (q *Queries) SetRefundPending(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setRefundPending, id)
	return err
}

const setRefundSucceeded = `-- name: SetRefundSucceeded :exec
UPDATE refunds SET status = 'succeeded', provider_refund_id = $1, updated_at = now()
WHERE id = $2
`

type SetRefundSucceededParams struct {
	ProviderRefundID *string
	ID               string
}

func (q *Queries) SetRefundSucceeded(ctx context.Context, arg SetRefundSucceededParams) error {
	_, err := q.db.Exec(ctx, setRefundSucceeded, arg.ProviderRefundID, arg.ID)
	return err
}
