// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package idempotencydb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claim = `-- name: Claim :execrows
INSERT INTO idempotency_keys (scope, key, request_hash)
VALUES ($1, $2, $3)
ON CONFLICT (scope, key) DO NOTHING
`

type ClaimParams struct {
	Scope       string
	Key         string
	RequestHash []byte
}

// Занимает ключ. 0 строк — ключ уже есть (выполнен, выполняется или брошен).
func (q *Queries) Claim(ctx context.Context, arg ClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, claim, arg.Scope, arg.Key, arg.RequestHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const complete = `-- name: Complete :exec
UPDATE idempotency_keys
SET response_status = $1, response_body = $2,
    response_content_type = $3, completed_at = now()
WHERE scope = $4 AND key = $5
`

type CompleteParams struct {
	ResponseStatus      pgtype.Int4
	ResponseBody        []byte
	ResponseContentType pgtype.Text
	Scope               string
	Key                 string
}

func (q *Queries) Complete(ctx context.Context, arg CompleteParams) error {
	_, err := q.db.Exec(ctx, complete,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ResponseContentType,
		arg.Scope,
		arg.Key,
	)
	return err
}

const get = `-- name: Get :one
SELECT request_hash, response_status, response_body, response_content_type, created_at, completed_at
FROM idempotency_keys
WHERE scope = $1 AND key = $2
`

type GetParams struct {
	Scope string
	Key   string
}

type GetRow struct {
	RequestHash         []byte
	ResponseStatus      pgtype.Int4
	ResponseBody        []byte
	ResponseContentType pgtype.Text
	CreatedAt           time.Time
	CompletedAt         *time.Time
}

func (q *Queries) Get(ctx context.Context, arg GetParams) (GetRow, error) {
	row := q.db.QueryRow(ctx, get, arg.Scope, arg.Key)
	var i GetRow
	err := row.Scan(
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ResponseContentType,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const release = `-- name: Release :exec
DELETE FROM idempotency_keys
WHERE scope = $1 AND key = $2 AND completed_at IS NULL
`

type ReleaseParams struct {
	Scope string
	Key   string
}

// Снимает незавершённый ключ, чтобы клиент мог повторить запрос.
func (q *Queries) Release(ctx context.Context, arg ReleaseParams) error {
	_, err := q.db.Exec(ctx, release, arg.Scope, arg.Key)
	return err
}

const releaseStale = `-- name: ReleaseStale :execrows
DELETE FROM idempotency_keys
WHERE scope = $1 AND key = $2 AND completed_at IS NULL AND created_at < $3
`

type ReleaseStaleParams struct {
	Scope       string
	Key         string
	StaleBefore time.Time
}

// Снимает ключ, брошенный упавшим процессом.
func (q *Queries) ReleaseStale(ctx context.Context, arg ReleaseStaleParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseStale, arg.Scope, arg.Key, arg.StaleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
